#
# Alembic migration script
#
"""
Revision ID: 80d7b35f6349
Revises: beef464253de
Create Date: 2025-08-15 21:54:10.728300

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d7b35f6349'
down_revision = 'beef464253de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
