#
# Alembic migration script
#
"""
Revision ID: beef464253de
Revises: 
Create Date: 2025-08-15 11:19:51.097471

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beef464253de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
